name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x, 14.x, 13.x, 12.x]
    steps:
      - name: Test
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        name: Cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run tsc --noEmit
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - uses: actions/cache@v2
        name: Cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm ci
      - name: Lint
        run: npm run lint
